---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xvwa-deployment
  labels:
    app: xvwa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xvwa
  template:
    metadata:
      labels:
        app: xvwa
    spec:
      containers:
      - name: xvwa
        image: tuxotron/xvwa
        ports:
        - containerPort: 80
