---
apiVersion: v1
kind: Service
metadata:
  name: web-dvwa
  namespace: vuln
  labels:
    app: web-dvwa
spec:
  type: NodePort
  selector:
    app: web-dvwa
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30666
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-dvwa-deployment
  namespace: vuln
  labels:
    app: web-dvwa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-dvwa
  template:
    metadata:
      labels:
        app: web-dvwa
    spec:
      containers:
      - name: web-dvwa
        image: vulnerables/web-dvwa
        ports:
        - containerPort: 80
